env:
    RUBY_VERSION: "3.4.5"
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
    DATABASE_USER: postgres
    DATABASE_PASSWORD: password
  
name: Rails tests
on: [push, pull_request]
jobs:
    rspec-test:
        name: RSpec
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:17
                ports:
                    - "5432:5432"
                env:
                    POSTGRES_USER: ${{ env.POSTGRES_USER }}
                    POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        steps:
            - uses: actions/checkout@v2

            - uses: ruby/setup-ruby@v1
              with:
                ruby-version: ${{ env.RUBY_VERSION }}

            - name: Install postgres client
              run: sudo apt-get update && sudo apt-get install -y libpq-dev

            - name: Install dependencies
              run: |
                gem install bundler
                bundle install

            - name: Create database
              run: |
                bundle exec rails db:create RAILS_ENV=test
                bundle exec rails db:migrate RAILS_ENV=test

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: "20"

            - name: Install yarn dependencies
              run: yarn install

            - name: Run tests
              run: bundle exec rspec .

            - name: Run brakeman
              run: brakeman -o brakeman.txt

            - name: Run rubocop
              run: bundle exec rubocop --force-exclusion vendor/*/** --out rubocop.txt

            - name: Upload coverage results
              uses: actions/upload-artifact@master
              if: always()
              with:
                name: coverage-report
                path: coverage

            - name: Upload rubocop report
              uses: actions/upload-artifact@master
              if: always()
              with:
                name: rubocop-report.txt
                path: rubocop.txt

            - name: Upload brakeman report
              uses: actions/upload-artifact@master
              if: always()
              with:
                name: brakeman-report.txt
                path: brakeman.txt